mongo:
    host: 192.168.1.6
    port: 27017
    db: gateway

alexaIp: 192.168.1.10

server:
    maxThreads: 10
    port: 8080

upnp:
    ttl: 10
    timeout: 1000
    port: 1900
    gateway: 0.0.0.0
    broadcastIp: 239.255.255.250
